version: "3"
services:
  frontend:
    image: node:fermium-buster
    container_name: ts-react-setup-sample
    working_dir: /home/ts-react-setup-sample
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/home/ts-react-setup-sample
      - node_modules_volume:/home/ts-react-setup-sample/node_modules
volumes:
  node_modules_volume:
