version: 2.1

orbs:
  node: circleci/node@4.1
  codecov: codecov/codecov@1.1.3

workflows:
  build-and-test:
    jobs:
      - node/test:
          version: 14.16.0
          pkg-manager: yarn
          run-command: test:cov
          post-steps:
            - store_artifacts:
                path: coverage
            - codecov/upload:
                file: ./coverage/lcov.info
